# Generated by Django 5.1.3 on 2025-12-12 18:22

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0002_alter_evaluation_options_alter_reservation_options_and_more",
        ),
        ("users", "0003_alter_administrator_department_alter_user_created_at_and_more"),
        ("vehicles", "0002_maintenancerecord_alter_vehicle_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_conversations",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Texte"),
                            ("image", "Image"),
                            ("location", "Position GPS"),
                            ("file", "Fichier"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("attachment_url", models.URLField(blank=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Diagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identified_issue", models.CharField(max_length=200)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Mineur"),
                            ("moderate", "Modéré"),
                            ("severe", "Sévère"),
                            ("critical", "Critique"),
                        ],
                        max_length=20,
                    ),
                ),
                ("symptoms_found", models.JSONField(default=list)),
                ("obd_codes", models.JSONField(default=list)),
                ("parts_needed", models.JSONField(default=list)),
                ("estimated_repair_time_hours", models.FloatField()),
                (
                    "estimated_labor_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estimated_parts_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estimated_total_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("can_repair_onsite", models.BooleanField(default=False)),
                (
                    "recommended_repair_location",
                    models.CharField(
                        choices=[
                            ("onsite", "Sur place"),
                            ("workshop", "En atelier"),
                            ("specialized", "Atelier spécialisé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("repair_location_reason", models.TextField(blank=True)),
                ("photos", models.JSONField(default=list)),
                ("videos", models.JSONField(default=list)),
                ("detailed_report", models.TextField()),
                ("recommendations", models.TextField(blank=True)),
                ("requires_immediate_attention", models.BooleanField(default=False)),
                ("safe_to_drive", models.BooleanField(default=True)),
                ("client_approved", models.BooleanField(blank=True, null=True)),
                ("client_approval_date", models.DateTimeField(blank=True, null=True)),
                ("client_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Diagnostic",
                "verbose_name_plural": "Diagnostics",
                "db_table": "diagnostics",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "towing_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "diagnosis_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "parts_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "labor_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("balance_due", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("partial", "Partiellement payée"),
                            ("paid", "Payée"),
                            ("refunded", "Remboursée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("line_items", models.JSONField(default=list)),
                ("warranty_months_parts", models.IntegerField(default=0)),
                ("warranty_months_labor", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "invoices",
            },
        ),
        migrations.CreateModel(
            name="TechnicianAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("max_bookings", models.IntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "technician_availabilities",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TripTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technician_current_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("estimated_arrival_time", models.DateTimeField(blank=True, null=True)),
                ("distance_remaining_km", models.FloatField(blank=True, null=True)),
                ("travel_duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Non démarré"),
                            ("en_route", "En route"),
                            ("arrived", "Arrivé"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("location_history", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Suivi de trajet",
                "verbose_name_plural": "Suivis de trajet",
                "db_table": "trip_tracking",
            },
        ),
        migrations.CreateModel(
            name="WorkProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inspection", "Inspection initiale"),
                            ("diagnosis", "Diagnostic en cours"),
                            ("parts_ordering", "Commande de pièces"),
                            ("parts_received", "Pièces reçues"),
                            ("repair_in_progress", "Réparation en cours"),
                            ("testing", "Tests et réglages"),
                            ("completed", "Travaux terminés"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("photos", models.JSONField(default=list)),
                ("videos", models.JSONField(default=list)),
                ("client_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Avancement travaux",
                "verbose_name_plural": "Avancements travaux",
                "db_table": "work_progress",
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="evaluation",
            name="evaluations_created_73d096_idx",
        ),
        migrations.RemoveIndex(
            model_name="reservation",
            name="reservation_created_0fc9f4_idx",
        ),
        migrations.AddField(
            model_name="evaluation",
            name="communication_rating",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evaluation",
            name="diagnosis_quality_rating",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evaluation",
            name="response_time_rating",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evaluation",
            name="value_for_money",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evaluation",
            name="would_recommend",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="actual_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="actual_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="can_restart",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_notified_arrival",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_notified_completion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="client_notified_diagnosis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="dashboard_warnings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="reservation",
            name="deposit_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="reservation",
            name="estimated_price_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="estimated_price_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="includes_towing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="location_description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Description lieu"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="photos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="reservation",
            name="scheduled_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("emergency", "Panne urgente"),
                    ("diagnosis", "Diagnostic"),
                    ("roadside_repair", "Dépannage sur place"),
                    ("towing", "Remorquage"),
                    ("scheduled_maintenance", "Révision planifiée"),
                    ("specific_repair", "Réparation spécifique"),
                    ("preventive_maintenance", "Entretien préventif"),
                ],
                default=3,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="symptoms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="reservation",
            name="towing_destination",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="reservation",
            name="towing_distance_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="urgency_level",
            field=models.CharField(
                choices=[
                    ("low", "Normal"),
                    ("medium", "Important"),
                    ("high", "Urgent"),
                    ("critical", "Critique"),
                ],
                default="low",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="warranty_months",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="commentaire",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="note",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="professionalism",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="punctuality",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="quality",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="intervention_type",
            field=models.CharField(
                blank=True,
                default="diagnostic_general",
                max_length=100,
                verbose_name="Type d'intervention",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("confirmed", "Confirmée"),
                    ("technician_dispatched", "Technicien en route"),
                    ("technician_arrived", "Technicien arrivé"),
                    ("in_progress", "En cours"),
                    ("diagnosis_submitted", "Diagnostic soumis"),
                    ("awaiting_client_approval", "En attente approbation client"),
                    ("parts_ordered", "Pièces commandées"),
                    ("ready_for_pickup", "Prêt pour récupération"),
                    ("completed", "Terminée"),
                    ("cancelled", "Annulée"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["service_type", "urgency_level"],
                name="reservation_service_b83c2a_idx",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="reservations.chatconversation",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic",
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="technician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.technician"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="technicianavailability",
            name="technician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="users.technician",
            ),
        ),
        migrations.AddField(
            model_name="triptracking",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_tracking",
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="workprogress",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_progress",
                to="reservations.reservation",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_messag_convers_0a903c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="technicianavailability",
            unique_together={("technician", "date", "start_time")},
        ),
    ]
