# Generated by Django 5.1.3 on 2025-11-28 17:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        ("users", "0003_alter_administrator_department_alter_user_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, default="", verbose_name="Commentaire"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Avis",
                "verbose_name_plural": "Avis",
                "db_table": "avis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="commande",
            options={
                "ordering": ["-date"],
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
            },
        ),
        migrations.AlterModelOptions(
            name="lignecommande",
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
            },
        ),
        migrations.AlterModelOptions(
            name="piece",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Pièce détachée",
                "verbose_name_plural": "Pièces détachées",
            },
        ),
        migrations.AlterModelOptions(
            name="produit",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
            },
        ),
        migrations.AddField(
            model_name="commande",
            name="date_expedition",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'expédition"
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="date_livraison",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de livraison"
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="date_paiement",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de paiement"
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="frais_livraison",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Frais de livraison",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="commande",
            name="notes_admin",
            field=models.TextField(
                blank=True, default="", verbose_name="Notes administrateur"
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("paid", "Payée"),
                    ("failed", "Échouée"),
                    ("refunded", "Remboursée"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut paiement",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="telephone_livraison",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="Téléphone livraison",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="piece",
            name="compatibilite",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des véhicules compatibles",
                verbose_name="Compatibilité",
            ),
        ),
        migrations.AddField(
            model_name="piece",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="piece",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="piece",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="produit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="produit",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Produit vedette"),
        ),
        migrations.AddField(
            model_name="produit",
            name="marque",
            field=models.CharField(blank=True, max_length=100, verbose_name="Marque"),
        ),
        migrations.AddField(
            model_name="produit",
            name="reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Référence"
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="adresse_livraison",
            field=models.TextField(
                blank=True, default="", verbose_name="Adresse de livraison"
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commandes",
                to="users.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de commande"
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="id",
            field=models.CharField(
                editable=False, max_length=50, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="prix_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Prix total"
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("processing", "En traitement"),
                    ("shipped", "Expédiée"),
                    ("delivered", "Livrée"),
                    ("cancelled", "Annulée"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="lignecommande",
            name="commande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="marketplace.commande",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="lignecommande",
            name="prix_unitaire",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Prix unitaire"
            ),
        ),
        migrations.AlterField(
            model_name="lignecommande",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.produit",
                verbose_name="Produit",
            ),
        ),
        migrations.AlterField(
            model_name="lignecommande",
            name="quantite",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantité",
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="id",
            field=models.CharField(
                editable=False, max_length=50, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="nom",
            field=models.CharField(max_length=200, verbose_name="Nom de la pièce"),
        ),
        migrations.AlterField(
            model_name="piece",
            name="prix",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prix",
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pieces",
                to="marketplace.produit",
                verbose_name="Produit associé",
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="reference",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Référence"
            ),
        ),
        migrations.AlterField(
            model_name="piece",
            name="stock",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Stock",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronic", "Électronique"),
                    ("mechanic", "Mécanique"),
                    ("accessory", "Accessoire"),
                    ("tool", "Outil"),
                    ("part", "Pièce détachée"),
                    ("other", "Autre"),
                ],
                max_length=50,
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="produit",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="produit",
            name="id",
            field=models.CharField(
                editable=False, max_length=50, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="images",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Images (URLs)"
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="nom",
            field=models.CharField(max_length=200, verbose_name="Nom du produit"),
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prix",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="stock",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Stock disponible",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="vendeur",
            field=models.ForeignKey(
                limit_choices_to={"user_type__in": ["vendor", "administrator"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendeur",
            ),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(
                fields=["client", "status"], name="commandes_client__44f656_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(fields=["status"], name="commandes_status_afaadb_idx"),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(
                fields=["payment_status"], name="commandes_payment_080d07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(fields=["date"], name="commandes_date_f5df09_idx"),
        ),
        migrations.AddIndex(
            model_name="piece",
            index=models.Index(fields=["reference"], name="pieces_referen_32f6a1_idx"),
        ),
        migrations.AddIndex(
            model_name="piece",
            index=models.Index(fields=["produit"], name="pieces_produit_e2fcad_idx"),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["is_active", "is_featured"], name="produits_is_acti_eb3e07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(fields=["nom"], name="produits_nom_b61b96_idx"),
        ),
        migrations.AddField(
            model_name="avis",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avis",
                to="users.client",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="avis",
            name="commande",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avis",
                to="marketplace.commande",
                verbose_name="Commande",
            ),
        ),
        migrations.AddField(
            model_name="avis",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avis",
                to="marketplace.produit",
                verbose_name="Produit",
            ),
        ),
        migrations.AddIndex(
            model_name="avis",
            index=models.Index(
                fields=["produit", "note"], name="avis_produit_e6d48c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="avis",
            unique_together={("produit", "client")},
        ),
    ]
