# Generated manually for marketplace_cartronic mobile API integration
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone


def seed_marketplace_vehicles(apps, schema_editor):
    MarketplaceVehicle = apps.get_model('marketplace', 'MarketplaceVehicle')
    vehicles = [
        {
            'id': 'MVH-DEMO-001',
            'name': 'Toyota Corolla',
            'brand': 'Toyota',
            'model': 'Corolla',
            'year': 2022,
            'type': 'rental',
            'price': 30000,
            'body_type': 'berline',
            'transmission': 'manuel',
            'fuel': 'gazoil',
            'seats': 5,
            'horsepower': 120,
            'features': ['Climatisation', 'Bluetooth/USB'],
            'location': 'Yaoundé',
            'images': ['https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=600'],
            'rating': 4.5,
            'review_count': 87,
            'partner_name': 'Cartronic',
            'description': 'Berline confortable et élégante, idéale pour la ville.',
            'is_active': True,
            'is_featured': True,
        },
        {
            'id': 'MVH-DEMO-002',
            'name': 'Toyota Hilux',
            'brand': 'Toyota',
            'model': 'Hilux',
            'year': 2021,
            'type': 'sale',
            'price': 2500000,
            'body_type': 'pick-up',
            'transmission': 'manuel',
            'fuel': 'gazoil',
            'seats': 5,
            'horsepower': 150,
            'features': ['Climatisation', '4x4'],
            'location': 'Yaoundé',
            'images': ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
            'rating': 4.8,
            'review_count': 124,
            'partner_name': 'Cartronic',
            'description': 'Pick-up robuste idéal pour tous les terrains.',
            'is_active': True,
            'is_featured': True,
        },
        {
            'id': 'MVH-DEMO-003',
            'name': 'Renault Espace',
            'brand': 'Renault',
            'model': 'Espace',
            'year': 2020,
            'type': 'rental',
            'price': 30000,
            'body_type': 'monospace',
            'transmission': 'manuel',
            'fuel': 'gazoil',
            'seats': 7,
            'horsepower': 110,
            'features': ['Climatisation', 'GPS'],
            'location': 'Douala',
            'images': ['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600'],
            'rating': 4.5,
            'review_count': 56,
            'partner_name': 'AutoRent',
            'description': 'Monospace spacieux parfait pour les familles.',
            'is_active': True,
            'is_featured': False,
        },
        {
            'id': 'MVH-DEMO-004',
            'name': 'BMW X5',
            'brand': 'BMW',
            'model': 'X5',
            'year': 2023,
            'type': 'sale',
            'price': 15000000,
            'body_type': 'suv',
            'transmission': 'automatique',
            'fuel': 'essence',
            'seats': 5,
            'horsepower': 250,
            'features': ['Climatisation', 'Bluetooth/USB', 'GPS', 'Cuir'],
            'location': 'Yaoundé',
            'images': ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600'],
            'rating': 4.9,
            'review_count': 34,
            'partner_name': 'LuxAuto',
            'description': 'SUV premium alliant performance et luxe.',
            'is_active': True,
            'is_featured': True,
        },
    ]
    for item in vehicles:
        vehicle_id = item.pop('id')
        MarketplaceVehicle.objects.update_or_create(id=vehicle_id, defaults=item)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('marketplace', '0003_marketplacearticletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceVehicle',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180, verbose_name='Nom commercial')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Année')),
                ('type', models.CharField(choices=[('sale', 'Vente'), ('rental', 'Location')], max_length=20, verbose_name='Type annonce')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix')),
                ('body_type', models.CharField(choices=[('berline', 'Berline'), ('suv', 'SUV'), ('pick-up', 'Pick-up'), ('monospace', 'Monospace'), ('citadine', 'Citadine'), ('cabriolet', 'Cabriolet')], default='berline', max_length=30, verbose_name='Carrosserie')),
                ('transmission', models.CharField(choices=[('manuel', 'Manuel'), ('automatique', 'Automatique')], default='manuel', max_length=30)),
                ('fuel', models.CharField(choices=[('gazoil', 'Gazoil'), ('essence', 'Essence'), ('electrique', 'Électrique'), ('hybride', 'Hybride')], default='essence', max_length=30, verbose_name='Carburant')),
                ('seats', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Places')),
                ('horsepower', models.PositiveIntegerField(default=0, verbose_name='Puissance')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Équipements')),
                ('location', models.CharField(blank=True, default='', max_length=150, verbose_name='Localisation')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Images')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'avis")),
                ('partner_name', models.CharField(blank=True, default='Cartronic', max_length=150, verbose_name='Nom partenaire')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['vendor', 'administrator']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_vehicles', to='users.user', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Véhicule marketplace',
                'verbose_name_plural': 'Véhicules marketplace',
                'db_table': 'marketplace_vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('vehicle_sale', 'Achat véhicule'), ('vehicle_rental', 'Location véhicule'), ('part', 'Pièces détachées')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('ready', 'Prête'), ('in_progress', 'En cours'), ('overdue', 'En retard'), ('delivered', 'Livrée'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('partially_paid', 'Partiellement payée'), ('refunded', 'Remboursée')], default='pending', max_length=30)),
                ('items', models.JSONField(blank=True, default=list)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='CFA', max_length=10)),
                ('rental_start_date', models.DateTimeField(blank=True, null=True)),
                ('rental_end_date', models.DateTimeField(blank=True, null=True)),
                ('actual_pickup_date', models.DateTimeField(blank=True, null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte'), ('orange_money', 'Orange Money'), ('mobile_money', 'Mobile Money')], default='', max_length=30)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('shipping_method', models.JSONField(blank=True, default=dict)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_orders', to='users.client')),
            ],
            options={
                'verbose_name': 'Commande marketplace mobile',
                'verbose_name_plural': 'Commandes marketplace mobile',
                'db_table': 'marketplace_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(model_name='marketplacevehicle', index=models.Index(fields=['type', 'is_active', 'is_featured'], name='marketplace_type_is_2c5b7e_idx')),
        migrations.AddIndex(model_name='marketplacevehicle', index=models.Index(fields=['brand', 'model'], name='marketplace_brand_0d26bb_idx')),
        migrations.AddIndex(model_name='marketplacevehicle', index=models.Index(fields=['price'], name='marketplace_price_c6c215_idx')),
        migrations.AddIndex(model_name='marketplacevehicle', index=models.Index(fields=['location'], name='marketplace_locatio_5f7494_idx')),
        migrations.AddIndex(model_name='marketplaceorder', index=models.Index(fields=['client', 'status'], name='marketplace_client__9843a4_idx')),
        migrations.AddIndex(model_name='marketplaceorder', index=models.Index(fields=['type', 'status'], name='marketplace_type_4a715d_idx')),
        migrations.AddIndex(model_name='marketplaceorder', index=models.Index(fields=['payment_status'], name='marketplace_payment_375087_idx')),
        migrations.AddIndex(model_name='marketplaceorder', index=models.Index(fields=['created_at'], name='marketplace_created_54f224_idx')),
        migrations.RunPython(seed_marketplace_vehicles, migrations.RunPython.noop),
    ]
