# Generated by Django 5.1.3 on 2026-04-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="payment_tra_reserva_ca8b2b_idx",
            old_name="payment_tr_reservat_67a6c8_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="payment_tra_status_ea288f_idx",
            old_name="payment_tr_status__71f5be_idx",
        ),
    ]
