# Generated by Django 5.1.3 on 2025-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marque", models.CharField(max_length=100)),
                ("modele", models.CharField(max_length=100)),
                ("type_vehicule", models.CharField(max_length=50)),
                ("annee", models.IntegerField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("statut", models.CharField(default="actif", max_length=50)),
            ],
            options={
                "db_table": "vehicles",
                "indexes": [
                    models.Index(
                        fields=["marque", "modele"], name="vehicles_marque_472948_idx"
                    )
                ],
            },
        ),
    ]
