# Generated by Django 5.1.3 on 2025-11-28 17:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_administrator_department_alter_user_created_at_and_more"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Date de l'intervention")),
                (
                    "type_maintenance",
                    models.CharField(
                        choices=[
                            ("vidange", "Vidange"),
                            ("revision", "Révision"),
                            ("reparation", "Réparation"),
                            ("diagnostic", "Diagnostic"),
                            ("entretien", "Entretien"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Type de maintenance",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cout",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Coût",
                    ),
                ),
                (
                    "kilometrage_actuel",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Kilométrage au moment de l'intervention",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes additionnelles"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Historique de maintenance",
                "verbose_name_plural": "Historiques de maintenance",
                "db_table": "maintenance_records",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Véhicule",
                "verbose_name_plural": "Véhicules",
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="couleur",
            field=models.CharField(blank=True, max_length=50, verbose_name="Couleur"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="kilometrage",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Kilométrage",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="numero_chassis",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Numéro de châssis (VIN)",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="numero_immatriculation",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Numéro d'immatriculation",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="proprietaires",
            field=models.ManyToManyField(
                blank=True,
                related_name="vehicules",
                to="users.client",
                verbose_name="Propriétaires",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="annee",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Année",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="marque",
            field=models.CharField(max_length=100, verbose_name="Marque"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="modele",
            field=models.CharField(max_length=100, verbose_name="Modèle"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="prix",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prix d'achat",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="statut",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("inactif", "Inactif"),
                    ("en_reparation", "En réparation"),
                    ("vendu", "Vendu"),
                ],
                default="actif",
                max_length=50,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="type_vehicule",
            field=models.CharField(
                choices=[
                    ("berline", "Berline"),
                    ("suv", "SUV"),
                    ("pickup", "Pick-up"),
                    ("van", "Utilitaire"),
                    ("moto", "Moto"),
                    ("camion", "Camion"),
                    ("autre", "Autre"),
                ],
                default="berline",
                max_length=50,
                verbose_name="Type de véhicule",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["numero_immatriculation"], name="vehicles_numero__ee2149_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["statut"], name="vehicles_statut_83677a_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["type_vehicule"], name="vehicles_type_ve_87ac90_idx"
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_done",
                to="users.technician",
                verbose_name="Technicien",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_records",
                to="vehicles.vehicle",
                verbose_name="Véhicule",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["vehicle", "date"], name="maintenance_vehicle_95a069_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["type_maintenance"], name="maintenance_type_ma_de90a4_idx"
            ),
        ),
    ]
