# Generated by Django 5.1.3 on 2025-12-12 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_administrator_department_alter_user_created_at_and_more"),
        ("vehicles", "0002_maintenancerecord_alter_vehicle_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="vehicle",
            name="vehicles_marque_472948_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="vehicles_numero__ee2149_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="vehicles_statut_83677a_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="vehicles_type_ve_87ac90_idx",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="marque",
            field=models.CharField(
                db_column="marque", max_length=100, verbose_name="Marque"
            ),
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="marque",
            new_name="brand",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="couleur",
            field=models.CharField(
                blank=True, db_column="couleur", max_length=50, verbose_name="Couleur"
            ),
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="couleur",
            new_name="color",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="numero_immatriculation",
            field=models.CharField(
                blank=True,
                db_column="numero_immatriculation",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Numéro d'immatriculation",
            ),
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="numero_immatriculation",
            new_name="license_plate",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="kilometrage",
            field=models.IntegerField(
                db_column="kilometrage",
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Kilométrage",
            ),
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="kilometrage",
            new_name="mileage",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="modele",
            field=models.CharField(
                db_column="modele", max_length=100, verbose_name="Modèle"
            ),
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="modele",
            new_name="model",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="statut",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("inactif", "Inactif"),
                    ("en_reparation", "En réparation"),
                    ("vendu", "Vendu"),
                ],
                db_column="statut",
                default="actif",
                max_length=50,
                verbose_name="Statut",
            ),
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="statut",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="numero_chassis",
            field=models.CharField(
                blank=True,
                db_column="numero_chassis",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Numéro de châssis (VIN)",
            ),
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="numero_chassis",
            new_name="vin",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="annee",
            field=models.IntegerField(
                db_column="annee",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Année",
            ),
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="annee",
            new_name="year",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="prix",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="type_vehicule",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="client",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="users.client",
                verbose_name="Propriétaire principal",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_service_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date dernier entretien"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_service_mileage",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Kilométrage dernier entretien"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(
                blank=True,
                db_column="prix",
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prix d'achat",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Berline"),
                    ("suv", "SUV"),
                    ("pickup", "Pick-up"),
                    ("van", "Fourgonnette"),
                    ("motorcycle", "Moto"),
                    ("truck", "Camion"),
                    ("autre", "Autre"),
                ],
                db_column="type_vehicule",
                default="sedan",
                max_length=50,
                verbose_name="Type de véhicule",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="proprietaires",
            field=models.ManyToManyField(
                blank=True,
                related_name="vehicules",
                to="users.client",
                verbose_name="Co-propriétaires",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["brand", "model"], name="vehicles_marque_472948_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["license_plate"], name="vehicles_numero__ee2149_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["status"], name="vehicles_statut_83677a_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["vehicle_type"], name="vehicles_type_ve_87ac90_idx"
            ),
        ),
    ]
