# Generated by Django 5.2.10 on 2026-06-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_vehiclecatalog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="vehiclecatalog",
            new_name="vehicle_cat_brand_445b0d_idx",
            old_name="vehicle_cata_brand_1dd95a_idx",
        ),
        migrations.RenameIndex(
            model_name="vehiclecatalog",
            new_name="vehicle_cat_gamme_67af8f_idx",
            old_name="vehicle_cata_gamme_8bee9e_idx",
        ),
    ]
