# Generated by Django 5.1.3 on 2025-11-19 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administrator",
            options={
                "verbose_name": "Administrateur",
                "verbose_name_plural": "Administrateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.AlterModelOptions(
            name="technician",
            options={
                "verbose_name": "Technicien",
                "verbose_name_plural": "Techniciens",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.RemoveField(
            model_name="client",
            name="vehicules",
        ),
        migrations.AddField(
            model_name="administrator",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Département"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("technician", "Technicien"),
                    ("vendor", "Vendeur"),
                    ("administrator", "Administrateur"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "business_license",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Licence commerciale"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                (
                    "total_sales",
                    models.IntegerField(default=0, verbose_name="Total des ventes"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendeur",
                "verbose_name_plural": "Vendeurs",
                "db_table": "vendors",
            },
        ),
    ]
