# Generated by Django 5.1.3 on 2025-11-28 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_administrator_options_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrator",
            name="department",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Département"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="business_license",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Licence commerciale",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="company_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Nom de l'entreprise",
            ),
        ),
    ]
