# Generated by Django 5.1.3 on 2026-02-10 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_administrator_department_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='TechnicianDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='technicians/documents/')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.technician')),
            ],
            options={
                'verbose_name': 'Document technicien',
                'verbose_name_plural': 'Documents techniciens',
                'db_table': 'technician_documents',
            },
        ),
    ]
