# Generated by Django 5.1.3 on 2026-04-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_merge_validation_workflow"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="SELECT 1;",
                    reverse_sql="SELECT 1;",
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="notification",
                    old_name="notificatio_user_id_3e4dd6_idx",
                    new_name="notificatio_user_id_7336fd_idx",
                ),
                migrations.RenameIndex(
                    model_name="notification",
                    old_name="notificatio_user_id_51d962_idx",
                    new_name="notificatio_user_id_6c7360_idx",
                ),
                migrations.RenameIndex(
                    model_name="pushtoken",
                    old_name="push_tokens_user_id_0f4d3a_idx",
                    new_name="push_tokens_user_id_acb118_idx",
                ),
                migrations.RenameIndex(
                    model_name="technician",
                    old_name="technicians_approva_fusion_idx",
                    new_name="technicians_approva_361fe2_idx",
                ),
            ],
        ),
    ]