# Generated by Django 5.2.10 on 2026-04-28 12:55

import apps.users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_technician_profile_photo_years_experience"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="technician",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Actif"),
                    ("rejected", "Refusé"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
