# Generated by Django 5.2.10 on 2026-06-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_profile_photo"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="techniciandocument",
            new_name="technician__technic_086a40_idx",
            old_name="techdoc_tech_status_idx",
        ),
        migrations.RenameIndex(
            model_name="techniciandocument",
            new_name="technician__documen_ca9b7a_idx",
            old_name="techdoc_type_idx",
        ),
    ]
