# Generated by Django 5.2.10 on 2026-04-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voice_calls", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="voicecallsession",
            new_name="voice_call__caller__a7a43b_idx",
            old_name="voice_call__caller__3f3c24_idx",
        ),
        migrations.RenameIndex(
            model_name="voicecallsession",
            new_name="voice_call__callee__aee1be_idx",
            old_name="voice_call__callee__9c2a14_idx",
        ),
        migrations.RenameIndex(
            model_name="voicecallsession",
            new_name="voice_call__reserva_afed35_idx",
            old_name="voice_call__reserva_8470b0_idx",
        ),
        migrations.RenameIndex(
            model_name="voicecallsignal",
            new_name="voice_call__session_709328_idx",
            old_name="voice_call__session_46674c_idx",
        ),
        migrations.RenameIndex(
            model_name="voicecallsignal",
            new_name="voice_call__sender__f21a18_idx",
            old_name="voice_call__sender__3a9225_idx",
        ),
    ]
