# Generated by Django 5.1.3 on 2026-02-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="admin_notif_destina_cc53c7_idx",
            old_name="notif_destinataire_lu_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="admin_notif_type_64d53d_idx",
            old_name="notif_type_idx",
        ),
        migrations.RenameIndex(
            model_name="signalement",
            new_name="signalement_status_dbd1c7_idx",
            old_name="signalement_status_type_idx",
        ),
        migrations.RenameIndex(
            model_name="signalement",
            new_name="signalement_utilisa_e89370_idx",
            old_name="signalement_user_vise_idx",
        ),
    ]
